[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
